catalyst/moodle-local_datacleaner

.travis.yml, README.md, classes/clean.php, cleaner/config/classes/clean.php, cleaner/config/settings.php, cleaner/config/tests/config_test.php, cleaner/sitedata/classes/supported_file_types.php
Changes to the cleaner_config subplugin to pass travis, also added unit tests
=> Refactored wheresql for cleaner_config and added unit tests

.travis.yml
Changes to travis config file to hopefully get around build errors, also we install the local_datacleaner plugin
=> Changes to .travis.yml

.travis.yml
I've moved away from trying to use the moodle-plugin-ci before it is installed, also we should probably test against both mysql and postgres
=> More changes to the travis config

index.php
=> Changed deprecated pix_url to pix_icon.

.travis.yml, cleaner/environment_matrix/classes/form/matrix.php, cleaner/environment_matrix/classes/local/matrix.php, cleaner/environment_matrix/db/install.xml, cleaner/environment_matrix/db/upgrade.php, cleaner/environment_matrix/index.php, cleaner/environment_matrix/lang/en/cleaner_environment_matrix.php, cleaner/environment_matrix/styles.css, cleaner/environment_matrix/version.php
This now ignores adding admin_setting_headings to the list of configurable items.
Improves the detection of textareas and how the area is rendered.
=> Issue #25: Environment matrix updates.

classes/clean.php, cleaner/replace_urls/classes/clean.php, cleaner/replace_urls/tests/replace_urls_test.php
-  Don't want to print output during unit tests
=> Add verbose mode for replace urls unit tests

.travis.yml, cleaner/scheduled_tasks/db/install.xml
=> Modify whitespace in cleaner/scheduled_tasks install.xml file #101

db/subplugins.json, db/subplugins.php
=> add subplugins.json support fixes #106

cli/clean.php, version.php
=> Added support for only running a single cleaner from cli #108

.travis.yml, cleaner/delete_users/classes/clean.php
=> Issue #113: Updated to clean contexts after user deletion

cleaner/backup/classes/clean.php, cleaner/backup/classes/privacy/provider.php, cleaner/backup/lang/en/cleaner_backup.php, cleaner/backup/settings.php, cleaner/backup/tests/cleaner_test.php, cleaner/backup/version.php
=> Issue #115: Added backup file deletion cleaner

.github/workflows/moodle-release.yml, version.php
- add moodle-release.yml file for automated releases
- bump version
=> Setup automated releases

cleaner/orphaned_sitedata/tests/unit/tempfiles_cleaner_test.php
=> fix: deprecation warning & use assertFileDoesNotExist instead

cleaner/config/tests/config_test.php, cleaner/orphaned_sitedata/tests/unit/tempfiles_cleaner_test.php
=> Fix deprecated calls in unit tests

README.md
This adds the new stable branch to the list of branches in the readme
=> [#152] Add MOODLE_311_STABLE branch to README (310 branch)

README.md
This adds the new stable branch to the list of branches in the readme
=> [#152] Add MOODLE_311_STABLE branch to README (master branch)

cleaner/users/classes/clean.php
Fixes #157 for the master branch
=> Fix error with scramble users module - master #157

cleaner/users/classes/clean.php
Fixes #157 for MOODLE_311_STABLE branch
=> Fix error with scramble users module - MOODLE_311_STABLE #157

cleaner/environment_matrix/classes/local/matrix.php
=> Search for all settings in config_plugins

index.php
=> MBS-7391: Replace the deprecated print_error by moodle exception

cleaner/custom_sql_post/settings.php, cleaner/custom_sql_pre/settings.php
Backport, see original pull request here https://github.com/catalyst/moodle-local_datacleaner/pull/170
Closes #169
=> issue #169: Add default settings for cleaner_custom_sql_pre and _post

cleaner/email/classes/clean.php
=> Make email suffix cleaner idempotent #176

cleaner/tasklogs/classes/privacy/provider.php
This PR addresses the issue in #188
=> Add privacy provider - cleaner_tasklogs

classes/clean.php, cli/clean.php, cli/lib.php
Fixed the SQL by removing the GROUP BY. 
Also tidied up a bit:
- removed the unnecessary constraint lastaccess < now
- removed the unnecessary COUNT query
- fixed bug in calling the abort_message method
- fixed the log to avoid attempting to create an already existing directory.
=> issue 195: fix SQL for checking recent logins
